# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [neverleans]
# open_collective: plug-store
# ko_fi: neverleans
# custom: ["https://plugstore.dev/pro"]
